### ISSUE TITLE
Why changing tracking-method also affects the number of detections? 

### ISSUE THREAD

**Issue by davide-bontempelli-zupit** [mikel-brostrom/boxmot#1641]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I ran boxmot keeping the same yolo model and only changing tracking method and on the video shown i got a lot less detections.

These are the two command that i used
```
python tracking/track.py --source "5042_5047.mp4" \ 
  --yolo-model yolov8x-pose.pt \
  --reid-model osnet_x1_0_msmt17.pt \
  --tracking-method botsort \
  --conf 0.1 \
  --iou 0.7 \
  --device 0 \
  --show \       
  --classes 0 \
  --name test \
  --exist-ok \ 
  --show-labels \      
  --show-conf \
  --show-trajectories \
  --save-txt \
  --line-width 3 \
  --verbose
  ```
  
  ```
  python tracking/track.py --source "5042_5047.mp4" \ 
  --yolo-model yolov8x-pose.pt \
  --reid-model osnet_x1_0_msmt17.pt \
  --tracking-method botsort \
  --conf 0.1 \
  --iou 0.7 \
  --device 0 \
  --show \     
  --classes 0 \
  --name test \
  --exist-ok \ 
  --show-labels \      
  --show-conf \
  --show-trajectories \
  --save-txt \
  --line-width 3 \
  --verbose
```

**Comment by mikel-brostrom** [comment]
The tracking modules themselves are doing some filtering on the detections in order to figure out wether they are good candidates to be accepted as valid tracks or not. Hence, affecting the number of outputs 😄. For example this line of code is relevant in BoTSORT:

https://github.com/mikel-brostrom/boxmot/blob/b349b6731ead2e22ec5bd791a31b74b40e338f80/boxmot/trackers/botsort/bot_sort.py#L278
