### ISSUE TITLE
how to  use object detection,meanwhile output the mAP

### ISSUE THREAD

**Issue by muzili-pengyang** [mikel-brostrom/boxmot#1767]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I want to  use  object detection, meanwhile want to see the mAP，but  I don't know how to go about displaying the detected mAP metrics during tracking

**Comment by lmaple24327** [comment]
> ### Search before asking
> * [x]  I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.
> 
> ### Question
> I want to use object detection, meanwhile want to see the mAP，but I don't know how to go about displaying the detected mAP metrics during tracking

May I ask how to solve this problem? I have downloaded the program of this warehouse, but this problem is displayed?

(boxmot) C:\Users\admin\Desktop\boxmot-master>python tracking/track.py --source 0 --yolo-model yolov8s.pt --classes 16 17
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\boxmot-master\tracking\track.py", line 11, in <module>
    from boxmot import TRACKERS
ModuleNotFoundError: No module named 'boxmot'
